CREATE TABLE ACCOUNT (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EMAIL VARCHAR(200) NOT NULL,
    NICKNAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(300) NOT NULL,
    CREATION TIMESTAMP NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID);
ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT_EMAIL UNIQUE (EMAIL);
ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT_NICKNAME UNIQUE (NICKNAME);

CREATE TABLE QUESTION (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDENTIFIER VARCHAR(8) NOT NULL,
    FULL_PATH VARCHAR(10000) NOT NULL,
    CREATION TIMESTAMP NOT NULL
);

ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY (ID);
ALTER TABLE QUESTION ADD CONSTRAINT UK_QUESTION_IDENTIFIER UNIQUE (IDENTIFIER);
ALTER TABLE QUESTION ADD CONSTRAINT UK_QUESTION_PATH UNIQUE (FULL_PATH);

CREATE TABLE ROOM (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDENTIFIER VARCHAR(9) NOT NULL,
    QUESTION_ID BIGINT,
    CREATION TIMESTAMP NOT NULL,
    LAST_ACTIVITY TIMESTAMP NOT NULL
);

ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM PRIMARY KEY (ID);
ALTER TABLE ROOM ADD CONSTRAINT UK_ROOM UNIQUE (IDENTIFIER);
ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID);

CREATE TABLE ANSWER (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ACCOUNT_ID BIGINT NOT NULL,
    QUESTION_ID BIGINT NOT NULL,
    GRADE SMALLINT NOT NULL,
    DURATION INTEGER NOT NULL,
    CREATION TIMESTAMP NOT NULL
);

ALTER TABLE ANSWER ADD CONSTRAINT PK_ANSWER PRIMARY KEY (ID);
ALTER TABLE ANSWER ADD CONSTRAINT FK_ANSWER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);
ALTER TABLE ANSWER ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID);


CREATE TABLE INTEREST (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ACCOUNT_ID BIGINT NOT NULL,
    FOLDER VARCHAR(10000) NOT NULL,
    CREATION TIMESTAMP NOT NULL
);

ALTER TABLE INTEREST ADD CONSTRAINT PK_INTEREST PRIMARY KEY (ID);
ALTER TABLE INTEREST ADD CONSTRAINT UK_INTEREST UNIQUE (ACCOUNT_ID, FOLDER);
ALTER TABLE INTEREST ADD CONSTRAINT FK_INTEREST_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

CREATE TABLE SESSION (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ROOM_ID  BIGINT NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    ANSWER VARCHAR(200),
    POINTS INTEGER NOT NULL,
    CREATION TIMESTAMP NOT NULL
);

ALTER TABLE SESSION ADD CONSTRAINT PK_SESSION PRIMARY KEY (ID);
ALTER TABLE SESSION ADD CONSTRAINT UK_SESSION UNIQUE (ROOM_ID, ACCOUNT_ID);
ALTER TABLE SESSION ADD CONSTRAINT FK_SESSION_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);
ALTER TABLE SESSION ADD CONSTRAINT FK_SESSION_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

