INSERT INTO ACCOUNT (USERNAME, PASSWORD, CREATION, MODIFIED) VALUES ('eduardo', 'eduardo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE USERNAME = 'eduardo'), '/disney', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT (USERNAME, PASSWORD, CREATION, MODIFIED) VALUES ('renata', 'renata', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE USERNAME = 'renata'), '/disney', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT (USERNAME, PASSWORD, CREATION, MODIFIED) VALUES ('beatriz', 'beatriz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE USERNAME = 'beatriz'), '/disney', CURRENT_TIMESTAMP);
