INSERT INTO ACCOUNT (EMAIL, NICKNAME, PASSWORD, CREATION) VALUES ('edupalermo@gmail.com', 'Eduardo', '$2y$12$rrMzsYg29LANR4g0I2kIAe3znv6vUtWS3ei8xtFeEVmrDLXqsQkES', CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'edupalermo@gmail.com'), '/disney', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT (EMAIL, NICKNAME, PASSWORD, CREATION) VALUES ('refalcao@gmail.com', 'Renatinha', '$2y$12$6qqmamP6zzEULC2lnj0lZuh4hBytKE9PlqkRYPEZC5F1Ia8Duqose', CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'refalcao@gmail.com'), '/disney', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT (EMAIL, NICKNAME, PASSWORD, CREATION) VALUES ('biapalermo@gmail.com', 'Lindinha', '$2y$12$ENzq48Yr7jlSsXbSxHc94Oywvr1pcnVy14FwLAmhjFHZyXvAxl9CS', CURRENT_TIMESTAMP);
INSERT INTO INTEREST (ACCOUNT_ID, FOLDER, CREATION) VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'biapalermo@gmail.com'), '/disney', CURRENT_TIMESTAMP);
